spring:
  application:
    name: demo-service

# PushGateway
management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          shutdown-operation: push
  endpoints:
    web:
      exposure:
        include: prometheus